name: Cypress Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - uat

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          build: pnpm build
          start: pnpm start
          browser: chrome
